"$schema" = 'https://starship.rs/config-schema.json'

format = """$all$directory$character"""

[hostname]
disabled = false
format = "on [$hostname](bold red) "
ssh_only = false
ssh_symbol = "ğŸŒ "
trim_at = ".local"

[username]
disabled = false
format = "[$user]($style) "
show_always = true
style_root = "red bold"
style_user = "blue bold"

[direnv]
disabled = false
